name: Trigger Lambda

on:
  push:
    branches:
      - master
    paths:
      - 'src/main/java/com/brillio/**/*.java'
      - 'src/main/resources/static/*.html'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Invoke Lambda function
        run: |
          PAYLOAD='{"owner": "KGSSV",
                "token": "${{ secrets.MY_TOKEN }}",
                "repo": "smartbank",
                "branch": "master"}'
          ENCODED_PAYLOAD=$(echo -n $PAYLOAD | base64)

          aws lambda invoke \
            --function-name automatetesting \
            --payload "$ENCODED_PAYLOAD" \
            --invocation-type Event \
            response.json
