name: Run Unit Test

on:
  push:
    branches:
      - master
    paths:
      - 'src/test/java/com/brillio/*.java'

jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jdk
          echo "export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64" >> $GITHUB_ENV
          echo "export PATH=\${JAVA_HOME}/bin:\${PATH}" >> $GITHUB_ENV

      - name: Build with Maven
        run: mvn clean package
        
  Test:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jdk
          echo "export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64" >> $GITHUB_ENV
          echo "export PATH=\${JAVA_HOME}/bin:\${PATH}" >> $GITHUB_ENV

      - name: Build and Test with Maven
        run: mvn test

      - name: Archive test reports
        uses: actions/upload-artifact@v2
        with:
          name: test-reports
          path: target/surefire-reports/
